//
// ********************************************************************
// * License and Disclaimer                                           *
// *                                                                  *
// * This product includes software developed by Members of the       *
// * Geant4 Collaboration ( https://geant4.web.cern.ch ).             *
// *                                                                  *
// * This product is a template code for Geant4 generated by          *
// * G4Starter (https://github.com/yourusername/G4Starter).           *
// *                                                                  *
// ********************************************************************
//

#include "DetectorConstruction.hh"
{%- if cookiecutter.physics_list_type == "custom" %}
#include "PhysicsList.hh"
{%- elif cookiecutter.physics_list_type == "factory" %}
#include "G4PhysListFactory.hh"
{%- else %}
#include "QBBC.hh"
{%- endif %}
#include "ActionInitialization.hh"

#include "G4RunManagerFactory.hh"
#include "G4UImanager.hh"
#include "G4VisExecutive.hh"
#include "G4UIExecutive.hh"

int main(int argc, char **argv)
{
    // Detect interactive mode (if no arguments) and define UI session
    //
    G4UIExecutive *ui = nullptr;
    if (argc == 1)
        ui = new G4UIExecutive(argc, argv);

    // Construct run manager
{%- if cookiecutter.use_multithreading == "true" %}
    auto runManager = G4RunManagerFactory::CreateRunManager(G4RunManagerType::Default);
{%- else %}
    auto runManager = G4RunManagerFactory::CreateRunManager(G4RunManagerType::Serial);
{%- endif %}

    // Set mandatory initialization classes
    runManager->SetUserInitialization(new DetectorConstruction);
{%- if cookiecutter.physics_list_type == "custom" %}
    runManager->SetUserInitialization(new PhysicsList);
{%- elif cookiecutter.physics_list_type == "factory" %}
    G4PhysListFactory factory;
    auto physicsList = factory.GetReferencePhysList("{{ cookiecutter.physics_factory_name }}");
    runManager->SetUserInitialization(physicsList);
{%- else %}
    runManager->SetUserInitialization(new QBBC);
{%- endif %}
    runManager->SetUserInitialization(new ActionInitialization);

    // Initialize G4 kernel
    runManager->Initialize();

    // Initialize visualization
    auto visManager = new G4VisExecutive;
    visManager->Initialize();

    // Get the pointer to the User Interface manager
    auto UImanager = G4UImanager::GetUIpointer();

    // Process macro or start UI session
    if (ui)
    {
        // interactive mode
        UImanager->ApplyCommand("/control/execute vis.mac");
        ui->SessionStart();
        delete ui;
    }
    else
    {
        // batch mode
        G4String command = "/control/execute ";
        G4String filename = argv[1];
        UImanager->ApplyCommand(command + filename);
    }

    // Job termination
    // Free the store: user actions, physics_list and detector_description are
    // owned and deleted by the run manager, so they should not be deleted
    // in the main() program !
    delete visManager;
    delete runManager;

    return 0;
}
